### ISSUE TITLE
Example on how to use register

### ISSUE THREAD

**Issue by nicopace** [undwad/conf0#1]
Could you implement a test that shows how to use the _register function?
Thanks!!

**Comment by undwad** [comment]
Please look at **test_register.lua** sample.
You can run **test_browse.lua**, wait until it lists all existing services then run **test_register.lua**.
**test_browse.lua** should report of new service named !!!CONF0 TEST SERVICE!!!.
Just now tested on windows 10.

**Comment by nicopace** [comment]
Excelent, thanks!!
